// Generated by tools/sync-caption-tokens.mjs — do not edit.
// Source of truth: packages/ui/src/tokens.css. Re-run after changing a caption token.
//
// One mapping is an approximation and is worth knowing about: a CSS text-shadow's
// blur length and a SwiftUI shadow's radius are not the same quantity. They are
// carried across 1:1 because that is the pairing the Stage 0 overlay was judged by
// eye against the web captions — a spec-correct blur/2 would visibly thin them.
import SwiftUI

enum CaptionTokens {
    /// The caption is a film subtitle: two lines, centred, never a paragraph.
    static let sizeMin: CGFloat = 20.0
    static let sizeMax: CGFloat = 30.0
    /// The vw term of the same clamp, as a fraction. On a Mac the screen is the viewport.
    static let sizeViewportFactor: CGFloat = 0.024
    static let leading: CGFloat = 1.35
    /// Tracking is stored in em because it is size-relative — Apple's rule that
    /// tracking is size-specific, not one value for every size.
    static let trackingEm: CGFloat = 0.005
    static let weight = Font.Weight.semibold            // --cap-weight: 600
    static let maxLines = 2
    static let maxCharsPerLine = 42
    /// Vertical centre of the caption, as a fraction of the screen from the top.
    static let centreFraction: CGFloat = 0.84
    static let fade: Double = 0.18

    /// Motif 5, The Ground: near-black, a narrow grey ramp, and ONE accent whose only
    /// meaning is settled. If ember appears more than a few times on a screen, it is
    /// being misused.
    enum Palette {
        static let ground = Color(.sRGB, red: 0.0392156862745098, green: 0.0392156862745098, blue: 0.0392156862745098, opacity: 1.0)
        static let raise = Color(.sRGB, red: 0.07450980392156863, green: 0.07450980392156863, blue: 0.07450980392156863, opacity: 1.0)
        static let line = Color(.sRGB, red: 0.13725490196078433, green: 0.13725490196078433, blue: 0.13725490196078433, opacity: 1.0)
        static let lineStrong = Color(.sRGB, red: 0.2, green: 0.2, blue: 0.2, opacity: 1.0)
        static let ink = Color(.sRGB, red: 0.9568627450980393, green: 0.9529411764705882, blue: 0.9450980392156862, opacity: 1.0)
        static let dim = Color(.sRGB, red: 0.5490196078431373, green: 0.5490196078431373, blue: 0.5490196078431373, opacity: 1.0)
        static let faint = Color(.sRGB, red: 0.4666666666666667, green: 0.4666666666666667, blue: 0.4666666666666667, opacity: 1.0)
        static let ember = Color(.sRGB, red: 1.0, green: 0.30196078431372547, blue: 0.058823529411764705, opacity: 1.0)
        static let emberDim = Color(.sRGB, red: 0.47843137254901963, green: 0.1411764705882353, blue: 0.03137254901960784, opacity: 1.0)
        static let ok = Color(.sRGB, red: 0.3568627450980392, green: 0.8156862745098039, blue: 0.5411764705882353, opacity: 1.0)
        static let warn = Color(.sRGB, red: 0.9098039215686274, green: 0.7803921568627451, blue: 0.47843137254901963, opacity: 1.0)
        static let bad = Color(.sRGB, red: 1.0, green: 0.30196078431372547, blue: 0.30196078431372547, opacity: 1.0)
    }

    struct Shadow: Equatable, Sendable {
        var x: CGFloat
        var y: CGFloat
        var radius: CGFloat
        var color: Color
    }

    struct Preset: Equatable, Sendable {
        var fontName: String
        var fontWeight: Double
        var italic: Bool
        var color: Color
        var shadows: [Shadow]
        /// A plate behind the text. Only Contrast has one; it breaks the no-box rule
        /// on purpose, because legibility beats the aesthetic.
        var backdrop: Color?
        var padding: EdgeInsets
    }

    static let classic = Preset(
        fontName: "Helvetica Neue",
        fontWeight: 600.0,
        italic: false,
        color: Color(.sRGB, red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0),
        shadows: [
            .init(x: 0.0, y: 1.0, radius: 2.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.9)),
            .init(x: 0.0, y: 2.0, radius: 14.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.75)),
        ],
        backdrop: nil,
        padding: EdgeInsets(top: 0.0, leading: 0.0, bottom: 0.0, trailing: 0.0)
    )

    static let warm = Preset(
        fontName: "Helvetica Neue",
        fontWeight: 500.0,
        italic: true,
        color: Color(.sRGB, red: 0.9686274509803922, green: 0.8745098039215686, blue: 0.40784313725490196, opacity: 1.0),
        shadows: [
            .init(x: 0.0, y: 0.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 1.0, y: 0.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: -1.0, y: 0.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 0.0, y: 1.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 0.0, y: -1.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 0.0, y: 2.0, radius: 12.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.7)),
        ],
        backdrop: nil,
        padding: EdgeInsets(top: 0.0, leading: 0.0, bottom: 0.0, trailing: 0.0)
    )

    static let contrast = Preset(
        fontName: "Menlo",
        fontWeight: 400.0,
        italic: false,
        color: Color(.sRGB, red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0),
        shadows: [
            // none — the plate carries legibility instead
        ],
        backdrop: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.82),
        padding: EdgeInsets(top: 4.0, leading: 14.0, bottom: 4.0, trailing: 14.0)
    )
}
