// Generated by tools/sync-caption-tokens.mjs — do not edit.
// Source of truth: packages/ui/src/tokens.css. Re-run after changing a caption token.
//
// One mapping is an approximation and is worth knowing about: a CSS text-shadow's
// blur length and a SwiftUI shadow's radius are not the same quantity. They are
// carried across 1:1 because that is the pairing the Stage 0 overlay was judged by
// eye against the web captions — a spec-correct blur/2 would visibly thin them.
import SwiftUI

enum CaptionTokens {
    /// The caption is a film subtitle: two lines, centred, never a paragraph.
    static let sizeMin: CGFloat = 20.0
    static let sizeMax: CGFloat = 30.0
    /// The vw term of the same clamp, as a fraction. On a Mac the screen is the viewport.
    static let sizeViewportFactor: CGFloat = 0.024
    static let leading: CGFloat = 1.45
    /// Tracking is stored in em because it is size-relative — Apple's rule that
    /// tracking is size-specific, not one value for every size.
    static let trackingEm: CGFloat = 0.005
    static let weight = Font.Weight.regular            // --cap-weight: 400
    static let maxLines = 2
    static let maxCharsPerLine = 42
    /// Vertical centre of the caption, as a fraction of the screen from the top.
    static let centreFraction: CGFloat = 0.78
    static let fade: Double = 0.18

    struct Shadow: Equatable, Sendable {
        var x: CGFloat
        var y: CGFloat
        var radius: CGFloat
        var color: Color
    }

    struct Preset: Equatable, Sendable {
        var color: Color
        var shadows: [Shadow]
        /// A plate behind the text. Only Contrast has one; it breaks the no-box rule
        /// on purpose, because legibility beats the aesthetic.
        var backdrop: Color?
        var padding: EdgeInsets
    }

    static let classic = Preset(
        color: Color(.sRGB, red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0),
        shadows: [
            .init(x: 0.0, y: 1.0, radius: 2.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.9)),
            .init(x: 0.0, y: 2.0, radius: 14.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.75)),
        ],
        backdrop: nil,
        padding: EdgeInsets(top: 0.0, leading: 0.0, bottom: 0.0, trailing: 0.0)
    )

    static let warm = Preset(
        color: Color(.sRGB, red: 0.9607843137254902, green: 0.7843137254901961, blue: 0.4196078431372549, opacity: 1.0),
        shadows: [
            .init(x: 0.0, y: 0.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 1.0, y: 0.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: -1.0, y: 0.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 0.0, y: 1.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 0.0, y: -1.0, radius: 1.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.95)),
            .init(x: 0.0, y: 2.0, radius: 12.0, color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.7)),
        ],
        backdrop: nil,
        padding: EdgeInsets(top: 0.0, leading: 0.0, bottom: 0.0, trailing: 0.0)
    )

    static let contrast = Preset(
        color: Color(.sRGB, red: 1.0, green: 1.0, blue: 1.0, opacity: 1.0),
        shadows: [
            // none — the plate carries legibility instead
        ],
        backdrop: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.82),
        padding: EdgeInsets(top: 4.0, leading: 14.0, bottom: 4.0, trailing: 14.0)
    )
}
